server:
  port: 8080

spring:
  application:
    name: drone-management-backend
  
  # 数据库配置
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dronedb}
    username: ${SPRING_DATASOURCE_USERNAME:drone}
    password: ${SPRING_DATASOURCE_PASSWORD:dronepassword}
    driver-class-name: org.postgresql.Driver
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# InfluxDB 配置
influxdb:
  url: ${INFLUXDB_URL:http://localhost:8086}
  token: ${INFLUXDB_TOKEN:my-super-secret-token}
  org: ${INFLUXDB_ORG:drone_org}
  bucket: ${INFLUXDB_BUCKET:drone_data}

# MQTT 配置
mqtt:
  broker:
    url: ${MQTT_BROKER_URL:tcp://localhost:1883}
  client:
    id: drone-backend
  username: ${MQTT_USERNAME:}
  password: ${MQTT_PASSWORD:}
  topics:
    telemetry: drones/+/telemetry
    commands: drones/+/commands
    responses: drones/+/responses
  connection:
    keepalive: 60
    timeout: 30
    auto-reconnect: true
    clean-session: true
    max-inflight: 100

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

# 日志配置
logging:
  level:
    com.huang: ${LOGGING_LEVEL_COM_HUANG:INFO}
    org.eclipse.paho: ${LOGGING_LEVEL_PAHO:INFO}
    org.springframework.web: INFO 