server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true

spring:
  application:
    name: drone-management-backend
  
  # 数据库配置
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:dronedb}
    username: ${POSTGRES_USER:drone}
    password: ${POSTGRES_PASSWORD:dronepassword}
    driver-class-name: org.postgresql.Driver
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# JWT配置
jwt:
  secret: ${JWT_SECRET:qGVbYmXnuLmZpWxNeChDkRbVeAvYzZrTfUoMsPdLwQqCgJiKjHkPlMnBvCxFzYaS}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours

# InfluxDB 配置
influxdb:
  url: ${INFLUXDB_URL:http://localhost:8086}
  token: ${INFLUXDB_TOKEN:my-super-secret-token}
  org: ${INFLUXDB_ORG:drone_org}
  bucket: ${INFLUXDB_BUCKET:drone_data}

# MQTT配置
mqtt:
  broker.url: ${MQTT_BROKER_URL:tcp://localhost:1883}
  username: ${MQTT_USERNAME:admin}
  password: ${MQTT_PASSWORD:public}
  client-id: ${MQTT_CLIENT_ID:backend-service}
  timeout: 10
  keep-alive: 60
  auto-reconnect: true

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /management
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
  health:
    defaults:
      enabled: true

# 应用信息
info:
  app:
    name: ${spring.application.name}
    description: 无人机管理系统后端
    version: 0.1.0

# 日志配置
logging:
  level:
    root: INFO
    com.huang: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/drone-management.log 